# Generated by Django 5.0.7 on 2024-07-31 13:17

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('date_of_birth', models.DateField(verbose_name='Date of Birth')),
                ('identification_number', models.CharField(max_length=20, unique=True, verbose_name='Identification Number')),
                ('gender', models.CharField(choices=[('MA', 'Male'), ('FE', 'Female'), ('UN', 'Unknown')], default='UN', max_length=2, verbose_name='Gender')),
                ('address', models.CharField(max_length=100, verbose_name='Address')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Phone Number')),
                ('has_whatsapp', models.BooleanField(default=False, verbose_name='Has Whatsapp?')),
                ('whatsapp_notification', models.BooleanField(default=False, verbose_name='Whatsapp Notification?')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('email_notification', models.BooleanField(default=False, verbose_name='Email Notification?')),
            ],
        ),
    ]
