# Generated by Django 5.0.7 on 2024-07-31 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_insurances', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification', models.CharField(blank=True, max_length=50, null=True, verbose_name='Identification')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('health_insurance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='health_insurances.healthinsurance', verbose_name='Patient')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='patients.patient', verbose_name='Patient')),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='health_insurances',
            field=models.ManyToManyField(related_name='patients', through='patients.Membership', to='health_insurances.healthinsurance', verbose_name='Health Insurances'),
        ),
    ]
