# Generated by Django 5.0.7 on 2024-08-02 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_membership_patient_health_insurances'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='plan',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Plan'),
        ),
    ]
