# Generated by Django 5.0.7 on 2024-07-31 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthInsurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='Code')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Website')),
                ('authorizer', models.CharField(choices=[('MA', 'Manual')], max_length=2, verbose_name='Authorizer')),
                ('nbu_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='NBU price')),
                ('coinsurance_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Coinsurance price')),
            ],
        ),
    ]
