# Generated by Django 5.0.7 on 2024-08-02 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health_insurances', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthinsurance',
            name='coinsurance_price',
        ),
    ]
