# Generated by Django 5.0.7 on 2024-07-31 18:35

import django.db.models.deletion
import django_extensions.db.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_insurances', '0001_initial'),
        ('patients', '0002_membership_patient_health_insurances'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Code')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('short_name', models.CharField(max_length=40, verbose_name='Short Name')),
                ('ub', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='UB')),
                ('reference_value', models.CharField(max_length=50, verbose_name='Reference Value')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='report',
            name='delivery_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Delivery Datetime'),
        ),
        migrations.AddField(
            model_name='report',
            name='health_insurances',
            field=models.ManyToManyField(to='health_insurances.healthinsurance'),
        ),
        migrations.AddField(
            model_name='report',
            name='order',
            field=models.FileField(blank=True, null=True, upload_to='orders', verbose_name='Order'),
        ),
        migrations.AddField(
            model_name='report',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='patients.patient'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='receipt',
            field=models.FileField(blank=True, null=True, upload_to='receipts', verbose_name='Receipt'),
        ),
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('DR', 'Draft'), ('ST', 'Started'), ('FI', 'Finished'), ('SU', 'Notified')], default='DR', max_length=2),
        ),
        migrations.AlterField(
            model_name='report',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Praxis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Code')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('standard', models.TextField(blank=True, verbose_name='Standard')),
                ('render', models.TextField(blank=True, verbose_name='Render')),
                ('measurements', models.ManyToManyField(blank=True, to='reports.measurement', verbose_name='Measurements')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReportMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('nbu_quantity', models.PositiveSmallIntegerField(default=1)),
                ('result', models.CharField(blank=True, max_length=255, null=True, verbose_name='Result')),
                ('measurements', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports.measurement')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports.report')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='report',
            name='measurements',
            field=models.ManyToManyField(related_name='reports', through='reports.ReportMeasurement', to='reports.measurement'),
        ),
        migrations.CreateModel(
            name='ReportPraxis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('health_insurance', models.ManyToManyField(to='health_insurances.healthinsurance')),
                ('praxis', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports.praxis')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports.report')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='report',
            name='praxis',
            field=models.ManyToManyField(related_name='reports', through='reports.ReportPraxis', to='reports.praxis'),
        ),
    ]
