# Generated by Django 5.0.7 on 2024-08-02 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_insurances', '0002_remove_healthinsurance_coinsurance_price'),
        ('reports', '0002_measurement_report_delivery_datetime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportmeasurement',
            name='nbu_quantity',
        ),
        migrations.RemoveField(
            model_name='reportpraxis',
            name='health_insurance',
        ),
        migrations.AddField(
            model_name='report',
            name='coinsurance_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Coinsurance price'),
        ),
        migrations.AddField(
            model_name='report',
            name='deposit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Deposit'),
        ),
        migrations.AddField(
            model_name='reportpraxis',
            name='status',
            field=models.CharField(choices=[('PE', 'Pending'), ('R', 'Rejected'), ('A', 'Approved'), ('AP', 'Audit Pending'), ('AA', 'Audit Approved'), ('AR', 'Audit Rejected'), ('PA', 'Particular')], default='PE', max_length=2),
        ),
        migrations.RemoveField(
            model_name='report',
            name='health_insurances',
        ),
        migrations.AlterField(
            model_name='report',
            name='measurements',
            field=models.ManyToManyField(blank=True, null=True, related_name='reports', through='reports.ReportMeasurement', to='reports.measurement'),
        ),
        migrations.AlterField(
            model_name='report',
            name='praxis',
            field=models.ManyToManyField(blank=True, null=True, related_name='reports', through='reports.ReportPraxis', to='reports.praxis'),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('DR', 'Draft'), ('CR', 'Created'), ('VE', 'Verified')], default='DR', max_length=2),
        ),
        migrations.AddField(
            model_name='report',
            name='health_insurances',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='health_insurances.healthinsurance'),
        ),
    ]
