# Generated by Django 5.0.7 on 2024-08-02 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_remove_reportmeasurement_nbu_quantity_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportmeasurement',
            options={},
        ),
        migrations.AlterModelOptions(
            name='reportpraxis',
            options={},
        ),
        migrations.RenameField(
            model_name='reportmeasurement',
            old_name='measurements',
            new_name='measurement',
        ),
        migrations.AlterField(
            model_name='report',
            name='measurements',
            field=models.ManyToManyField(blank=True, related_name='reports', through='reports.ReportMeasurement', to='reports.measurement'),
        ),
        migrations.AlterField(
            model_name='report',
            name='praxis',
            field=models.ManyToManyField(blank=True, related_name='reports', through='reports.ReportPraxis', to='reports.praxis'),
        ),
        migrations.AlterUniqueTogether(
            name='reportmeasurement',
            unique_together={('report', 'measurement')},
        ),
        migrations.AlterUniqueTogether(
            name='reportpraxis',
            unique_together={('report', 'praxis')},
        ),
    ]
