# Generated by Django 5.0.7 on 2024-08-02 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_alter_reportmeasurement_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportmeasurement',
            name='measurement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.measurement'),
        ),
        migrations.AlterField(
            model_name='reportmeasurement',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.report'),
        ),
        migrations.AlterField(
            model_name='reportpraxis',
            name='praxis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.praxis'),
        ),
        migrations.AlterField(
            model_name='reportpraxis',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.report'),
        ),
    ]
