# Generated by Django 5.0.7 on 2024-08-06 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_alter_reportmeasurement_measurement_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='health_insurances',
            new_name='health_insurance',
        ),
    ]
